//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisorFacturas.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisorFacturas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_blue_arrow_left_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_blue_arrow_left_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_blue_arrow_right_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_blue_arrow_right_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_blue_goto_next_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_blue_goto_next_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_blue_goto_previous_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_blue_goto_previous_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_circle_blue_first_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_circle_blue_first_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_circle_blue_last_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_circle_blue_last_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_circle_blue_left_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_circle_blue_left_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_circle_blue_right_24x24 {
            get {
                object obj = ResourceManager.GetObject("button_circle_blue_right_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comisión_Nacional_de_Zonas_Francas {
            get {
                object obj = ResourceManager.GetObject("Comisión_Nacional_de_Zonas_Francas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CZF_Logo {
            get {
                object obj = ResourceManager.GetObject("CZF_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export_spreadsheet_32x32 {
            get {
                object obj = ResourceManager.GetObject("export_spreadsheet_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter_32x32 {
            get {
                object obj = ResourceManager.GetObject("filter_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gobierno {
            get {
                object obj = ResourceManager.GetObject("Gobierno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_32x32 {
            get {
                object obj = ResourceManager.GetObject("info_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prev_32x32 {
            get {
                object obj = ResourceManager.GetObject("prev_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print_24x24 {
            get {
                object obj = ResourceManager.GetObject("print_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer_32x32 {
            get {
                object obj = ResourceManager.GetObject("printer_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove_32x32 {
            get {
                object obj = ResourceManager.GetObject("remove_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send_32x32 {
            get {
                object obj = ResourceManager.GetObject("send_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TraExt_btn {
            get {
                object obj = ResourceManager.GetObject("TraExt_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TraFin_btn {
            get {
                object obj = ResourceManager.GetObject("TraFin_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Watermark_Comisión_Nacional_de_Zonas_Francas {
            get {
                object obj = ResourceManager.GetObject("Watermark_Comisión_Nacional_de_Zonas_Francas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Watermark_CZF_Logo {
            get {
                object obj = ResourceManager.GetObject("Watermark_CZF_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///CLI.cli_cod AS &apos;cli_cod&apos;
        ///,CLI.cli_nom AS &apos;cli_nombre&apos;
        ///,UPPER(CLI.cli_regime) AS &apos;tipo_reg&apos;
        ///,FAC.fecha AS &apos;fac_fecha&apos;
        ///,FAC.fac_fac_nu AS &apos;fac_numfac&apos;
        ///,FAC.fac_amo_do as &apos;factotd&apos;
        ///,NVL(PAG.pg_amo_dol, 0) as &apos;pag_totd&apos;
        ///,NVL(PAG.pg_recnum, &apos;&apos;) AS &apos;pag_numroc&apos;
        ///,NVL(PAG.pg_fecpag, CTOD(&apos;&apos;)) AS &apos;pag_fecha&apos;
        ///,FAC.Debe as &apos;fac_debe&apos;
        ///FROM FACTURA AS FAC
        ///INNER JOIN CLIENTE AS CLI ON FAC.CLI_CODIG = CLI.CLI_COD
        ///LEFT JOIN PAGOS AS PAG ON (FAC.fac_fac_nu = PAG.pg_factura AND FAC.CLI_CODIG = PAG.pg_cod [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string xr_proc_antiguedad_sdo {
            get {
                return ResourceManager.GetString("xr_proc_antiguedad_sdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///CLI.cli_cod AS &apos;cli_cod&apos;
        ///,CLI.cli_nom AS &apos;cli_nombre&apos;
        ///,UPPER(CLI.cli_regime) AS &apos;tipo_reg&apos;
        ///,&apos;Saldo Inicial&apos; as &apos;concept&apos;
        ///,CTOD(&apos;&apos;) AS &apos;fac_fecha&apos;
        ///,1 AS &apos;fac_numfac&apos;
        ///,SUM(FAC.fac_amo_do) as &apos;fac_totd&apos; 
        ///,SUM(NVL((SELECT SUM(PAG.pg_amo_dol) from PAGOS as PAG where PAG.pg_factura=FAC.fac_fac_nu AND FAC.CLI_CODIG = PAG.pg_cod_cli), 0)) as &apos;pag_totd&apos;
        ///,&apos;&apos; AS &apos;pag_numroc&apos;
        ///,CTOD(&apos;&apos;) AS &apos;pag_fecha&apos;
        ///,7 as &apos;fac_debe&apos;
        ///FROM CLIENTE AS CLI 
        ///LEFT JOIN FACTURA AS FAC ON FAC.CLI_CODIG = CLI.CLI_COD
        ///WHER [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string xr_proc_estado_cuenta {
            get {
                return ResourceManager.GetString("xr_proc_estado_cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select
        ///CLI.cli_cod AS &apos;cli_cod&apos;
        ///,CLI.cli_nom AS &apos;cli_nombre&apos;
        ///,CAST(SUM(IIF(REM.rem_codig &lt;&gt; &apos;05TRAM01&apos;, REM.rem_canti, 0)) AS NUMERIC(10,2)) AS &apos;rem_cant&apos;
        ///,CAST(SUM(IIF(REM.rem_codig &lt;&gt; &apos;05TRAM01&apos;, REM.rem_canti * REM.rem_precio, 0)) AS NUMERIC(10,2)) AS &apos;rem_cantprecio&apos;
        ///,CAST(SUM(IIF(REM.rem_codig &lt;&gt; &apos;05TRAM01&apos;, REM.rem_descue, 0)) AS NUMERIC(10,2)) * -1 AS &apos;rem_descuen&apos;
        ///,CAST(SUM(IIF(REM.rem_codig = &apos;05TRAM01&apos;, REM.rem_canti * REM.rem_precio, 0)) AS NUMERIC(10,2)) AS &apos;rem_tramit&apos;
        ///,FAC.fac_amo_do as [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string xr_proc_facturas_compara_mes_act_ant {
            get {
                return ResourceManager.GetString("xr_proc_facturas_compara_mes_act_ant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select FAC.fac_fac_nu AS &apos;fac_numfac&apos;
        ///,FAC.fecha AS &apos;fac_fecha&apos;
        ///,CLI.cli_nom AS &apos;cli_nombre&apos;
        ///,CLI.cli_pais AS &apos;cli_pais&apos;
        ///,CLI.cli_ciudad AS &apos;cli_ciudad&apos;
        ///,CAST(SUM(IIF(REM.rem_codig &lt;&gt; &apos;05TRAM01&apos;, REM.rem_canti, 0)) AS NUMERIC(10,2)) AS &apos;rem_cant&apos;
        ///,CAST(SUM(IIF(REM.rem_codig &lt;&gt; &apos;05TRAM01&apos;, REM.rem_precio, 0)) AS NUMERIC(10,2)) AS &apos;rem_precio&apos;
        ///,CAST(SUM(IIF(REM.rem_codig &lt;&gt; &apos;05TRAM01&apos;, REM.rem_canti * REM.rem_precio, 0)) AS NUMERIC(10,2)) AS &apos;rem_cantprecio&apos;
        ///,CAST(SUM(IIF(REM.rem_codig &lt;&gt; &apos;05TRAM01&apos;,  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string xr_proc_facturas_mes {
            get {
                return ResourceManager.GetString("xr_proc_facturas_mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select CLI.cli_cod AS &apos;cli_cod&apos;
        ///,CLI.cli_nom AS &apos;cli_nombre&apos;
        ///,MONTH(FAC.fecha) AS &apos;fac_mesfact&apos;
        ///,SUM(NVL(REM.rem_canti, 0)) AS &apos;rem_cant&apos;
        ///from CLIENTE AS CLI
        ///INNER JOIN FACTURA AS FAC ON CLI.CLI_COD = FAC.CLI_CODIG 
        ///LEFT JOIN .\TempRemision\REMISION AS REM ON (FAC.ord_numero = REM.rem_numero AND REM.rem_codig not like &apos;%TRAM%&apos; AND MONTH(FAC.fecha) = MONTH(REM.rem_fecha))
        ///group by cli_cod, cli_nombre, fac_mesfact
        ///order by CLI.cli_nom 
        ///HAVING rem_cant &gt; 0  
        ///where YEAR(FAC.fecha) = {0}.
        /// </summary>
        internal static string xr_proc_metraje_anual {
            get {
                return ResourceManager.GetString("xr_proc_metraje_anual", resourceCulture);
            }
        }
    }
}
