//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisorFacturas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.25.23\\Contabilidad-CNZF\\Sisintfi\\CxC\\CZF")]
        public string DirectorioTablasCNZF {
            get {
                return ((string)(this["DirectorioTablasCNZF"]));
            }
            set {
                this["DirectorioTablasCNZF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\VFactCNZF\\Facturas")]
        public string DirectorioFacturasCNZF {
            get {
                return ((string)(this["DirectorioFacturasCNZF"]));
            }
            set {
                this["DirectorioFacturasCNZF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.25.23\\Contabilidad-CNZF\\Sisintfi\\CxC\\CZF\\TempRemision")]
        public string DirectorioTablasRemisionCNZF {
            get {
                return ((string)(this["DirectorioTablasRemisionCNZF"]));
            }
            set {
                this["DirectorioTablasRemisionCNZF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.25.23\\Contabilidad-CNZF\\SISINTFI\\AF\\ZFM")]
        public string DirectorioActivosFijosCNZF {
            get {
                return ((string)(this["DirectorioActivosFijosCNZF"]));
            }
            set {
                this["DirectorioActivosFijosCNZF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.25.23\\contabilidad\\APLIC\\SISINTFI\\PRICE\\INVENT\\CZF")]
        public string DirectorioTablasCZF {
            get {
                return ((string)(this["DirectorioTablasCZF"]));
            }
            set {
                this["DirectorioTablasCZF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\VFactCZF\\Facturas")]
        public string DirectorioFacturasCZF {
            get {
                return ((string)(this["DirectorioFacturasCZF"]));
            }
            set {
                this["DirectorioFacturasCZF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.25.23\\contabilidad\\APLIC\\SISINTFI\\PRICE\\INVENT\\CZF\\TempRemision")]
        public string DirectorioTablasRemisionCZF {
            get {
                return ((string)(this["DirectorioTablasRemisionCZF"]));
            }
            set {
                this["DirectorioTablasRemisionCZF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.25.23\\contabilidad\\APLIC\\SISINTFI\\PRICE\\AF\\ZFM")]
        public string DirectorioActivosFijosCZF {
            get {
                return ((string)(this["DirectorioActivosFijosCZF"]));
            }
            set {
                this["DirectorioActivosFijosCZF"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=VFPOLEDB.1;Data Source=\\\\192.168.25.23\\Contabilidad-CNZF\\Sisintfi\\CxC\\CZ" +
            "F;Extended Properties=dBASE IV;")]
        public string mCnxCNZF_TablasCXC {
            get {
                return ((string)(this["mCnxCNZF_TablasCXC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx")]
        public string VisorFacturas_ni_gob_bcn_servicios_Tipo_Cambio_BCN {
            get {
                return ((string)(this["VisorFacturas_ni_gob_bcn_servicios_Tipo_Cambio_BCN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=VFPOLEDB.1;Data Source=\\\\192.168.25.23\\contabilidad\\APLIC\\SISINTFI\\PRICE" +
            "\\INVENT\\CZF;Extended Properties=dBASE IV;")]
        public string mCnxCZF_TablasCXC {
            get {
                return ((string)(this["mCnxCZF_TablasCXC"]));
            }
        }
    }
}
