//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisorFacturas.DataNota
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAFWINEntities : DbContext
    {
        public SAFWINEntities()
            : base("name=SAFWINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NotasDC> NotasDC { get; set; }
    
        public virtual ObjectResult<dbo_pro_lst_NotasDC_Result> dbo_pro_lst_NotasDC(Nullable<int> pauidcia)
        {
            var pauidciaParameter = pauidcia.HasValue ?
                new ObjectParameter("pauidcia", pauidcia) :
                new ObjectParameter("pauidcia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dbo_pro_lst_NotasDC_Result>("dbo_pro_lst_NotasDC", pauidciaParameter);
        }
    }
}
