//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisorFacturas.DataNota
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasDC
    {
        public int Id { get; set; }
        public int Tipo { get; set; }
        public int Cont { get; set; }
        public string Num_nota { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Anno { get; set; }
        public int mes { get; set; }
        public string Codigo { get; set; }
        public string Cliente { get; set; }
        public string Ruc { get; set; }
        public string Concepto { get; set; }
        public byte[] ConceptoR { get; set; }
        public decimal Monto { get; set; }
        public string MontoLetra { get; set; }
        public string Elaborado { get; set; }
        public string Revisado { get; set; }
        public string Autorizado { get; set; }
        public bool Estado { get; set; }
        public int Id_empresa { get; set; }
        public int NumMoneda { get; set; }
    }
}
