using DevExpress.XtraEditors;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using VisorFacturas.Clases;
using DevExpress.XtraLayout;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Columns;
using DevExpress.Utils;

namespace VisorFacturas.Forms
{
    public partial class modal_frmVerificadas : DevExpress.XtraBars.ToolbarForm.ToolbarForm
    {
        List<viewVerificadas> factura;   //Esta se ocupa para los reportes
        public modal_frmVerificadas(List<viewVerificadas> aoFacV)
        {
            InitializeComponent();
            factura = aoFacV;
        }

        private void modal_frmVerificadas_Load(object sender, EventArgs e)
        {
            bsVerificacion.DataSource = factura;

            //gvFacturasV.Columns.Clear();

            //gvFacturasV.BeginUpdate();
            ////AutoGeneratedColumns(mMasterComp_grv);//Aquí construyo las columnas
            //AutoGeneratedColumns(gvFacturasV);
        }

        /// <summary>
        /// Ordeno las columnas en el grid de acuerdo a la entidad
        /// </summary>
        /// <param name="gvFacturasV"></param>
        private void AutoGeneratedColumns(GridView gvFacturasV)
        {
           
            //foreach (GridColumn column in gvFacturasV.Columns)
            //{

            //    #region Obtener Ancho y descripcion
            //    if (column.AbsoluteIndex != 0)
            //    {                   
            //        column.AppearanceHeader.Font = new System.Drawing.Font("Tahoma", 8.25F, FontStyle.Bold);
            //        column.AppearanceHeader.Options.UseFont = true;
            //        column.AppearanceHeader.Options.UseTextOptions = true;
            //        column.AppearanceHeader.TextOptions.HAlignment = HorzAlignment.Center;
            //        column.Caption = "Facturas que no cumplen";
            //        //column.Visible = true;                
            //        column.VisibleIndex = column.AbsoluteIndex - 1;
            //        column.FieldName = ""
            //        column.MaxWidth = 500;
            //        column.MinWidth = 500;
            //        column.Width = 500;
            //    }
            //    else
            //    {
            //        column.Visible = false;
            //    }

            //    #endregion

            //}
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                var aoSavcat = new SaveFileDialog { Filter = "Excel (2007) (*.xlsx)|*.xlsx", DefaultExt = ".xlsx", Title = "Exportando Listado de Facturas" };
                aoSavcat.ShowDialog();
                if (!String.IsNullOrEmpty(aoSavcat.FileName))
                {
                    string acFileName = aoSavcat.FileName;
                        
                    gcFacturasV.ExportToXlsx(acFileName);
                        
                    if (XtraMessageBox.Show("¿Desea abrir el archivo exportado?", "Abrir", MessageBoxButtons.YesNo,
                            MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        System.Diagnostics.Process.Start(aoSavcat.FileName);
                    }
                }

            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
            }
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //// XtraReport1 report = new XtraReport1();
            // ReportPrintTool printTool = new ReportPrintTool(Binding bs;
            // // Invoke the Print dialog.
            // printTool.PrintDialog();
            // // Send the report to the default printer.
            // printTool.Print();
            // // Send the report to the specified printer.
            // printTool.Print("myPrinter");
            ShowLayoutControlPreview(layoutControl1);
        }
        private void ShowLayoutControlPreview(LayoutControl layout)
        {
            // Check whether the LayoutControl can be previewed.
            if (!layout.IsPrintingAvailable)
            {
                MessageBox.Show("No se encuentra la biblioteca 'DevExpress.XtraPrinting'", "Error");
                return;
            }

            // Open the Preview window.
            layout.ShowPrintPreview();
        }

       
    }
}